/**
 *
 * @copyright Copyright (c) 2022 ApertureData Inc.
 *
 */

#pragma once

#include <string>

// must be called within a catch{} block
std::string print_caught_exception();
